apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: MAD.ocir.io/ax6nf8o6d4jv/book-service:latest 
        ports:
        - containerPort: 8081 
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/bookdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin 
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092 
      imagePullSecrets:
      - name: ocirsecret

---

apiVersion: v1
kind: Service
metadata:
  name: book-service 
  labels:
    app: book-service
spec:
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 8081 
      targetPort: 8081
  type: ClusterIP 
