apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: MAD.ocir.io/ax6nf8o6d4jv/cart-service:latest 
        ports:
        - containerPort: 8082 
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/cartdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin 
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
      imagePullSecrets:
      - name: ocirsecret

---

apiVersion: v1
kind: Service
metadata:
  name: cart-service 
  labels:
    app: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 8082 
      targetPort: 8082
  type: ClusterIP
