
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: docker.io/bitnami/kafka:3.5.2 
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181 
        - name: KAFKA_CFG_LISTENERS
          value: CLIENT://:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: CLIENT://kafka-service:9092 
        - name: KAFKA_CFG_ADVERTISED_HOST_NAME
          value: kafka-service 
        - name: KAFKA_CFG_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: CLIENT:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: CLIENT
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service 
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092 
      targetPort: 9092
  type: ClusterIP

