apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: MAD.ocir.io/ax6nf8o6d4jv/order-service:latest 
        ports:
        - containerPort: 8083 
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/orderdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin 
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092 
      imagePullSecrets:
      - name: ocirsecret

---

apiVersion: v1
kind: Service
metadata:
  name: order-service # Nome do serviço interno para resolução DNS
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8083 # Porta que o order-service expõe (para outros serviços o alcançarem)
      targetPort: 8083
  type: ClusterIP # Serviço interno, não exposto externamente
