# user-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: MAD.ocir.io/ax6nf8o6d4jv/user-service:latest 
        ports:
        - containerPort: 8085 
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/userdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin
        
      imagePullSecrets:
      - name: ocirsecret 

---

apiVersion: v1
kind: Service
metadata:
  name: user-service 
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8085 
      targetPort: 8085 
  type: ClusterIP
