server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:

        # Api Composition Checkout endpoints
       
        - id: composite-checkout
          uri: http://dummy-uri.org
          predicates:
            - Path=/gateway/checkout

        # Api Composition AddtoCart endpoints

        - id: composite-add-to-cart
          uri: http://dummy-uri.org
          predicates:
            - Path=/gateway/add-to-cart

        #  Api Composition ViewOrder endpoints
        - id: view_order_composite_route
          uri: http://dummy-uri.org
          predicates:
            - Path=/gateway/view-order/{orderId}

        # User-service endpoints

        - id: user-service
          uri: http://user-service:8085
          predicates:
            - Path=/auth/login

        - id: user-service
          uri: http://user-service:8085
          predicates:
            - Path=/auth/register

        - id: user-service
          uri: http://user-service:8085
          predicates:
            - Path=/user/**
            - Path=/id/**

        # Book-service endpoints

        - id: book-service
          uri: http://book-service:8081
          predicates:
            - Path=/books

        - id: book-service
          uri: http://book-service:8081
          predicates:
            - Path=/books/**

        - id: book-service
          uri: http://book-service:8081
          predicates:
            - Path=/author

        - id: book-service
          uri: http://book-service:8081
          predicates:
            - Path=/category

        - id: book-service
          uri: http://book-service:8081
          predicates:
            - Path=/subcategories
        
        - id: book-service
          uri: http://book-service:8081
          predicates:
            - Path=/search

        # Cart-service endpoints

        - id: cart-service
          uri: http://cart-service:8082
          predicates:
            - Path=/cart

        - id: cart-service
          uri: http://cart-service:8082
          predicates:
            - Path=/cartitem

        # Order-service endpoints
 
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/orders/checkout

app:
  jwtSecret: TXlTdXBlclNlY3JldEtleTEyMzQ1TXlTdXBlclNlY3JldEtleTEyMzQ1

logging:
  level:
    '[org.springframework.web.reactive.DispatcherHandler]': TRACE
    '[org.springframework.cloud.gateway]': DEBUG
    '[reactor.netty.http.server]': DEBUG